micronaut:
  application:
    name: api
#datasources:
#  default:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    db-type: mysql
netty:
  default:
    allocator:
      max-order: 3

hibernate:
  hbm2ddl:
    auto: create
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

jackson:
  serialization:
    writeDatesAsTimestamps: false
  dateFormat: YYYYMMdd