micronaut:
  application:
    name: app
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
dataSource:
  driverClassName: com.mysql.cj.jdbc.Driver
  pooled: true
  jmxExport: true
datasources.default.db-type: mysql
hibernate:
  hbm2ddl:
    auto: none
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
netty:
  default:
    allocator:
      max-order: 3
